### ISSUE TITLE
List index out of range while parsing SNC Patient report

### ISSUE THREAD

**Issue by mchamberland** [IQDM/IQDM-PDF#15]
This report (and I have many others like it) fails because (I think) the parser does not find a summary type (e.g., gamma analysis). This leads to a list index out of range when building the summary_data of the SNCPatientReport.

@cutright I think it'll be faster if you take a look. Thanks!

[19E-edit.PDF](https://github.com/IQDM/IQDM-PDF/files/5894868/19E-edit.PDF)

**Comment by mchamberland** [comment]
@cutright  And I just remembered you told me about the tolerance option. Setting it to 20 helped for this. I'll test with the remainder of my reports. Perhaps this should be explicitly added in the JSON template.

**Comment by cutright** [comment]
```
>>> from IQDMPDF.parsers.parser import ReportParser
>>> test_data = ReportParser("19E.PDF")
>>> test_data.report.data
```

Scanning down :

```
page_index: 0, data_index: 17
bbox: [6.24, 456.11, 140.33, 476.12]
Absolute Dose Comparison
% Diff
```

sncpatient.json expects summary type here:
`{"column": "Summary Type", "page": 0, "pos": [6.24, 359.5]},`

So the Y position is off quite a bit.

If you compare the Northwestern ArcCheck test data.  It look like the font sizes in 19E.pdf are larger.  Also, some rows in the Absolute Dose Comparison are in 19E.PDF that aren't in NM's PDF.

So, two options, we can create a new JSON template that works with 19E.PDF and have code figure out when to use which JSON file, or we can write a custom parser similar to Delta4 and Verisoft.

**Comment by mchamberland** [comment]
Oh yeah, I missed that those rows are different.

I think a new JSON template could work. I have hundreds of reports from 2016 - 2018 that are all similar to this one.

**Comment by mchamberland** [comment]
Obviously, disregard my previous comment about the tolerance since the rows are all screwed up. :)

**Comment by cutright** [comment]
I'm very confident a new JSON template would work for your institution, with the possible need for `alternates`.  I wonder how many variations there are for SNC... and why the font sizes are different?

But I think the long term solution is to tweak the `pdfminer.six` parameter so it picks up each block (QA File Parameter, Absolute Dose Comparison, etc.) as one block of data.  I don't know how to do that yet (but pretty sure I saw it on their GitHub).  Then do a custom parser similar to the VeriSoft parser where it finds "anchors" based on table headers/names.

But short term plan, lets do a new JSON template.  And then add a catch in `SNCPatientReport` to know when to pick the other JSON file?
https://github.com/IQDM/IQDM-PDF/blob/master/IQDMPDF/parsers/sncpatient.py

**Comment by cutright** [comment]
PS, thanks for working on this Marc!

**Comment by mchamberland** [comment]
It looks like we upgraded our version of SNC Patient sometime in early 2019 (to version 8.2) and that changed the reports and the font size. I *think* we were on 8.1 before. We have terrible record keeping for those things.

It does look like SNC frequently tweaks their reports.

**Comment by cutright** [comment]
Oh yeah... to handle the different row counts, we *could* include VanDyk in `identifiers`. That will lead us into having several JSON templates though.  Maybe that's preferable over custom parsers like verisoft and delta4?

What are your thoughts on JSON templating these vs a customized parser with `anchors`?

**Comment by cutright** [comment]
https://pdfminersix.readthedocs.io/en/latest/reference/composable.html#api-laparams

I think `line_margin` can be tweaked here, then we can search for those table headers to get the whole block at once.

Edit:
See use of `LAParams` in `IQDMPDF.pdf_reader.CustomPDFReader`:
https://github.com/IQDM/IQDM-PDF/blob/5320c11f121414cdfa001eba67a6e8f527d0aa3d/IQDMPDF/pdf_reader.py#L154-L199

I bet knowing that would have made the delta4 parser much less complicated.

**Comment by cutright** [comment]
This could work! I set `line_margin` to 1 (default is 0.5), and got this (output edited for brevity):

```
>>> from IQDMPDF.parsers.parser import ReportParser
>>> report = ReportParser("19E.PDF")
>>> report.report.data

page_index: 0, data_index: 0
bbox: [198.0, 599.73, 371.41, 610.77]
ArcCHECK QA of Dose Distribution

page_index: 0, data_index: 1
bbox: [439.89, 599.73, 700.93, 610.77]
Hospital Name: University of Vermont Medical Center

page_index: 0, data_index: 5
bbox: [6.23, 492.83, 97.62, 586.29]
QA File Parameter
Patient Name
Patient ID
Plan Date
SSD
Depth
Energy
Angle

page_index: 0, data_index: 6
bbox: [79.2, 492.83, 133.91, 574.31]
 :Anon, Anon^L
: 000XXXXXX
 : 7/9/2018
 : 
 : 
 : 10 MV
 : 

page_index: 0, data_index: 10
bbox: [6.24, 382.67, 140.33, 476.12]
Absolute Dose Comparison
% Diff
Distance (mm)
Threshold
Rotation Angle
Meas Uncertainty
Dose Diff Thresh
Use VanDyk

page_index: 0, data_index: 11
bbox: [79.2, 382.67, 118.22, 464.15]
 : 2
 : 3.0
 : 10.0
 : 0.0 Degs
 : Yes
 : 0.0 cGy
 : Yes

page_index: 0, data_index: 12
bbox: [79.2, 309.23, 103.73, 353.99]
 : 1386
 : 1323
 : 63
 : 95.5

page_index: 0, data_index: 13
bbox: [6.24, 296.99, 147.17, 365.96]
Summary (Gamma Analysis)
Total Points
Passed
Failed
% Passed
*DTA/Gamma is using 3D Mode

```

We'd need to let `convert_pdf_to_text` accept `LAParam` input, changing `line_margin` breaks the other parsers.

**Comment by mchamberland** [comment]
I like the idea of the JSON templates. There's something neat about it being generic and customizable without getting into the actual code.

**Comment by cutright** [comment]
I wonder if we can get by with just a new template for reports with VanDyk?  Even though your reports have different font sizes, I still wonder if another corner or center position is consistent.  Hopefully I'll have time to look into that this weekend.

**Comment by cutright** [comment]
I see no correlation with positions (any corner or center of boxes), I'll try to work up a custom parser similar to the verisoft parser today.  If I can get in the zone, should only take a couple hours.

**Comment by cutright** [comment]
I've got a method that extracts everything but the "Dose Values in cGy" table (which didn't have before anyway). I think that's doable, I'll add that later.  I'll push to a new branch later today.

**Comment by cutright** [comment]
@mchamberland Can you give this new branch a spin (v0.2.6)?
Pull Request: https://github.com/IQDM/IQDM-PDF/pull/16

**Comment by mchamberland** [comment]
@cutright  Thanks, Dan! I'll give that a shot.

**Comment by mchamberland** [comment]
@cutright   Seems to work great on about 900 reports! Thanks, Dan!

**Comment by cutright** [comment]
I'll push this to master.  We can save parsing the table in the bottom left of the report for another version.
